const data = {
    "pregnacy": [
        {
            "id": 1,
            "fetalHow": 'ground cinnamon',
            "imgFetal": 'fetal/1.png',
            "lengthFetal": 0,
            "weightFetal": 0,
            "abdomen": 'abdomen/1.png',
            "fetalHowImg": 'vegetables/1.png',
        },
        {
            "id": 2,
            "fetalHow": 'ground cinnamon',
            "imgFetal": 'fetal/2.png',
            "lengthFetal": 0,
            "weightFetal": 0,
            "abdomen": 'abdomen/1.png',
            "fetalHowImg": 'vegetables/1.png',
        },
        {
            "id": 3,
            "fetalHow": 'poppy seed',
            "imgFetal": 'fetal/3.png',
            "lengthFetal": 0.01,
            "weightFetal": 0.01,
            "abdomen": 'abdomen/1.png',
            "fetalHowImg": 'vegetables/3.png',
        },
        {
            "id": 4,
            "fetalHow": 'poppy seed',
            "imgFetal": 'fetal/14.png',
            "lengthFetal": 0.1,
            "weightFetal": 0.08,
            "abdomen": 'abdomen/1.png',
            "fetalHowImg": 'vegetables/4.png',
        },
        {
            "id": 5,
            "fetalHow": 'rice grain',
            "imgFetal": 'fetal/5.png',
            "lengthFetal": 0.2,
            "weightFetal": 0.2,
            "abdomen": 'abdomen/1.png',
            "fetalHowImg": 'vegetables/5.png',
        },
        {
            "id": 6,
            "fetalHow": 'bluberry',
            "imgFetal": 'fetal/6.png',
            "lengthFetal": 1,
            "weightFetal": 0.5,
            "abdomen": 'abdomen/1.png',
            "fetalHowImg": 'vegetables/6.png',
        },
        {
            "id": 7,
            "fetalHow": 'sunflower seed',
            "imgFetal": 'fetal/7.png',
            "lengthFetal": 1.2,
            "weightFetal": 0.7,
            "abdomen": 'abdomen/1.png',
            "fetalHowImg": 'vegetables/7.png',
        },
        {
            "id": 8,
            "fetalHow": 'blackberry',
            "imgFetal": 'fetal/8.png',
            "lengthFetal": 1.5,
            "weightFetal": 1.2,
            "abdomen": 'abdomen/1.png',
            "fetalHowImg": 'vegetables/8.png',
        },
        {
            "id": 9,
            "fetalHow": 'oliva',
            "imgFetal": 'fetal/9.png',
            "lengthFetal": 2.2,
            "weightFetal": 1.5,
            "abdomen": 'abdomen/1.png',
            "fetalHowImg": 'vegetables/9.png',
        },
        {
            "id": 10,
            "fetalHow": 'kumquat',
            "imgFetal": 'fetal/10.png',
            "lengthFetal": 5.5,
            "weightFetal": 5,
            "abdomen": 'abdomen/1.png',
            "fetalHowImg": 'vegetables/10.png',
        },
        {
            "id": 11,
            "fetalHow": 'apricot',
            "imgFetal": 'fetal/11.png',
            "lengthFetal": 6,
            "weightFetal": 9,
            "abdomen": 'abdomen/1.png',
            "fetalHowImg": 'vegetables/11.png',
        },
        {
            "id": 12,
            "fetalHow": 'peach',
            "imgFetal": 'fetal/12.png',
            "lengthFetal": 8,
            "weightFetal": 15,
            "abdomen": 'abdomen/1.png',
            "fetalHowImg": 'vegetables/12.png',
        },
        {
            "id": 13,
            "fetalHow": 'tomato',
            "imgFetal": 'fetal/13.png',
            "lengthFetal": 10,
            "weightFetal": 20,
            "abdomen": 'abdomen/1.png',
            "fetalHowImg": 'vegetables/13.png',
        },
        {
            "id": 14,
            "fetalHow": 'orange',
            "imgFetal": 'fetal/14.png',
            "lengthFetal": 12,
            "weightFetal": 30,
            "abdomen": 'abdomen/2.png',
            "fetalHowImg": 'vegetables/14.png',
        },
        {
            "id": 15,
            "fetalHow": 'pear',
            "imgFetal": 'fetal/15.png',
            "lengthFetal": 14,
            "weightFetal": 50,
            "abdomen": 'abdomen/2.png',
            "fetalHowImg": 'vegetables/15.png',
        },
        {
            "id": 16,
            "fetalHow": 'pomegranate',
            "imgFetal": 'fetal/16.png',
            "lengthFetal": 16,
            "weightFetal": 75,
            "abdomen": 'abdomen/2.png',
            "fetalHowImg": 'vegetables/16.png',
        },
        {
            "id": 17,
            "fetalHow": 'grapefruit',
            "imgFetal": 'fetal/17.png',
            "lengthFetal": 18,
            "weightFetal": 115,
            "abdomen": 'abdomen/2.png',
            "fetalHowImg": 'vegetables/17.png',
        },
        {
            "id": 18,
            "fetalHow": 'radish',
            "imgFetal": 'fetal/18.png',
            "lengthFetal": 20,
            "weightFetal": 160,
            "abdomen": 'abdomen/2.png',
            "fetalHowImg": 'vegetables/18.png',
        },
        {
            "id": 19,
            "fetalHow": 'carrot',
            "imgFetal": 'fetal/19.png',
            "lengthFetal": 22,
            "weightFetal": 215,
            "abdomen": 'abdomen/2.png',
            "fetalHowImg": 'vegetables/19.png',
        },
        {
            "id": 20,
            "fetalHow": 'turnip',
            "imgFetal": 'fetal/20.png',
            "lengthFetal": 24,
            "weightFetal": 270,
            "abdomen": 'abdomen/2.png',
            "fetalHowImg": 'vegetables/20.png',
        },
        {
            "id": 21,
            "fetalHow": 'pomelo',
            "imgFetal": 'fetal/21.png',
            "lengthFetal": 26,
            "weightFetal": 350,
            "abdomen": 'abdomen/2.png',
            "fetalHowImg": 'vegetables/21.png',
        },
        {
            "id": 22,
            "fetalHow": 'corn',
            "imgFetal": 'fetal/22.png',
            "lengthFetal": 27.5,
            "weightFetal": 410,
            "abdomen": 'abdomen/2.png',
            "fetalHowImg": 'vegetables/22.png',
        },
        {
            "id": 23,
            "fetalHow": 'coconut',
            "imgFetal": 'fetal/23.png',
            "lengthFetal": 29.5,
            "weightFetal": 500,
            "abdomen": 'abdomen/2.png',
            "fetalHowImg": 'vegetables/23.png',
        },
        {
            "id": 24,
            "fetalHow": 'eggplant',
            "imgFetal": 'fetal/24.png',
            "lengthFetal": 31,
            "weightFetal": 600,
            "abdomen": 'abdomen/2.png',
            "fetalHowImg": 'vegetables/24.png',
        },
        {
            "id": 25,
            "fetalHow": 'bunch of grapes',
            "imgFetal": 'fetal/25.png',
            "lengthFetal": 32,
            "weightFetal": 750,
            "abdomen": 'abdomen/2.png',
            "fetalHowImg": 'vegetables/25.png',
        },
        {
            "id": 26,
            "fetalHow": 'swede',
            "imgFetal": 'fetal/26.png',
            "lengthFetal": 33.5,
            "weightFetal": 850,
            "abdomen": 'abdomen/2.png',
            "fetalHowImg": 'vegetables/26.png',
        },
        {
            "id": 27,
            "fetalHow": 'papaya',
            "imgFetal": 'fetal/27.png',
            "lengthFetal": 35.5,
            "weightFetal": 1000,
            "abdomen": 'abdomen/2.png',
            "fetalHowImg": 'vegetables/27.png',
        },
        {
            "id": 28,
            "fetalHow": 'beet',
            "imgFetal": 'fetal/28.png',
            "lengthFetal": 37,
            "weightFetal": 1200,
            "abdomen": 'abdomen/3.png',
            "fetalHowImg": 'vegetables/28.png',
        },
        {
            "id": 29,
            "fetalHow": 'head of broccoli',
            "imgFetal": 'fetal/29.png',
            "lengthFetal": 38.5,
            "weightFetal": 1300,
            "abdomen": 'abdomen/3.png',
            "fetalHowImg": 'vegetables/29.png',
        },
        {
            "id": 30,
            "fetalHow": 'zucchini',
            "imgFetal": 'fetal/30.png',
            "lengthFetal": 40,
            "weightFetal": 1500,
            "abdomen": 'abdomen/3.png',
            "fetalHowImg": 'vegetables/30.png',
        },
        {
            "id": 31,
            "fetalHow": 'pineapple',
            "imgFetal": 'fetal/31.png',
            "lengthFetal": 41,
            "weightFetal": 1600,
            "abdomen": 'abdomen/3.png',
            "fetalHowImg": 'vegetables/31.png',
        },
        {
            "id": 32,
            "fetalHow": 'bunch of bananas',
            "imgFetal": 'fetal/32.png',
            "lengthFetal": 42.5,
            "weightFetal": 1800,
            "abdomen": 'abdomen/3.png',
            "fetalHowImg": 'vegetables/32.png',
        },
        {
            "id": 33,
            "fetalHow": 'lettuce',
            "imgFetal": 'fetal/33.png',
            "lengthFetal": 43.5,
            "weightFetal": 2000,
            "abdomen": 'abdomen/3.png',
            "fetalHowImg": 'vegetables/33.png',
        },
        {
            "id": 34,
            "fetalHow": 'melon',
            "imgFetal": 'fetal/34.png',
            "lengthFetal": 44.5,
            "weightFetal": 2100,
            "abdomen": 'abdomen/3.png',
            "fetalHowImg": 'vegetables/34.png',
        },
        {
            "id": 35,
            "fetalHow": 'head of cabbage',
            "imgFetal": 'fetal/35.png',
            "lengthFetal": 45.5,
            "weightFetal": 2300,
            "abdomen": 'abdomen/3.png',
            "fetalHowImg": 'vegetables/35.png',
        },
        {
            "id": 36,
            "fetalHow": 'vegetable marrow',
            "imgFetal": 'fetal/36.png',
            "lengthFetal": 46.5,
            "weightFetal": 2500,
            "abdomen": 'abdomen/3.png',
            "fetalHowImg": 'vegetables/36.png',
        },
        {
            "id": 37,
            "fetalHow": 'melon',
            "imgFetal": 'fetal/37.png',
            "lengthFetal": 48,
            "weightFetal": 2600,
            "abdomen": 'abdomen/3.png',
            "fetalHowImg": 'vegetables/37.png',
        },
        {
            "id": 38,
            "fetalHow": 'jackfruit',
            "imgFetal": 'fetal/38.png',
            "lengthFetal": 49,
            "weightFetal": 2600,
            "abdomen": 'abdomen/3.png',
            "fetalHowImg": 'vegetables/38.png',
        },
        {
            "id": 39,
            "fetalHow": 'pumpkin',
            "imgFetal": 'fetal/39.png',
            "lengthFetal": 50,
            "weightFetal": 3000,
            "abdomen": 'abdomen/3.png',
            "fetalHowImg": 'vegetables/39.png',
        },
        {
            "id": 40,
            "fetalHow": 'watermelon',
            "imgFetal": 'fetal/40.png',
            "lengthFetal": 54,
            "weightFetal": 3500,
            "abdomen": 'abdomen/3.png',
            "fetalHowImg": 'vegetables/40.png',
        },
    ]
}

export const fetchPregnant = (time = 1000) => {
    return new Promise((res) => {
        setTimeout(() => {
            res(data);
        }, time);
    });
};
